import type { Business } from './types';

export const businesses: Business[] = [
  {
    id: '1',
    slug: 'good-bread-pune',
    businessName: 'Good Bread',
    ownerName: 'Anand Kumar',
    businessAddress: 'FC Road',
    city: 'Pune',
    category: 'Restaurant',
    contactNumber: '9876543210',
    email: 'contact@goodbread.com',
    description: 'Serving the best artisanal bread and coffee in Pune. A perfect spot for breakfast and brunch.',
    rating: 5,
    isPremium: true,
    imageId: 'restaurant-1',
  },
  {
    id: '2',
    slug: 'mumbai-electronics',
    businessName: 'Mumbai Electronics',
    ownerName: 'Priya Sharma',
    businessAddress: 'Lamington Road',
    city: 'Mumbai',
    category: 'Electronics',
    contactNumber: '9123456789',
    email: 'support@mumbaielectronics.com',
    description: 'Your one-stop shop for all electronic needs. We offer the latest gadgets at competitive prices.',
    rating: 4,
    isPremium: false,
    imageId: 'electronics-1',
  },
  {
    id: '3',
    slug: 'nagpur-pharma',
    businessName: 'Nagpur Pharma',
    ownerName: 'Rajesh Gupta',
    businessAddress: 'Sitabuldi',
    city: 'Nagpur',
    category: 'Medical',
    contactNumber: '9988776655',
    email: 'orders@nagpurpharma.in',
    description: 'A reliable pharmacy providing a wide range of medicines and healthcare products 24/7.',
    rating: 4,
    isPremium: true,
    imageId: 'medical-1',
  },
  {
    id: '4',
    slug: 'pune-fashion-house',
    businessName: 'Pune Fashion House',
    ownerName: 'Sunita Patil',
    businessAddress: 'MG Road',
    city: 'Pune',
    category: 'Clothing',
    contactNumber: '9765432109',
    email: 'style@punefashion.com',
    description: 'Trendy and traditional apparel for all occasions. We believe in fashion that tells a story.',
    rating: 5,
    isPremium: false,
    imageId: 'clothing-1',
  },
  {
    id: '5',
    slug: 'quick-fix-mumbai',
    businessName: 'Quick Fix Services',
    ownerName: 'Amit Singh',
    businessAddress: 'Andheri West',
    city: 'Mumbai',
    category: 'Services',
    contactNumber: '9001122334',
    email: 'help@quickfix.com',
    description: 'Professional home repair and maintenance services. From plumbing to electrical, we handle it all.',
    rating: 4,
    isPremium: false,
    imageId: 'services-1',
  },
  {
    id: '6',
    slug: 'nagpur-eats',
    businessName: 'Nagpur Eats',
    ownerName: 'Meera Deshpande',
    businessAddress: 'Dharampeth',
    city: 'Nagpur',
    category: 'Restaurant',
    contactNumber: '9112233445',
    email: 'info@nagpureats.com',
    description: 'Authentic Vidarbha cuisine with a modern twist. Famous for our Saoji preparations.',
    rating: 5,
    isPremium: true,
    imageId: 'restaurant-2',
  },
  {
    id: '7',
    slug: 'gadget-guru-pune',
    businessName: 'Gadget Guru',
    ownerName: 'Vikram Rathore',
    businessAddress: 'Kothrud',
    city: 'Pune',
    category: 'Electronics',
    contactNumber: '9555666777',
    email: 'guru@gadgets.com',
    description: 'The best place for gadget repairs and accessories. Quick service and expert technicians.',
    rating: 4,
    isPremium: false,
    imageId: 'electronics-2',
  },
   {
    id: '8',
    slug: 'smile-care-mumbai',
    businessName: 'Smile Care Dental',
    ownerName: 'Dr. Aisha Khan',
    businessAddress: 'Bandra',
    city: 'Mumbai',
    category: 'Medical',
    contactNumber: '9332211009',
    email: 'apppointments@smilecare.com',
    description: 'State-of-the-art dental clinic offering a complete range of dental services with a gentle touch.',
    rating: 5,
    isPremium: true,
    imageId: 'medical-2',
  },
];
